# Generated by Django 5.2 on 2025-04-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_remove_user_is_admin_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='last_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='last_predicted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='last_prediction',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='last_recommendation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
