# Generated by Django 5.2 on 2025-04-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0003_patientrecord_last_confidence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelRetrainLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.FloatField()),
                ('retrained_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
